# x-logging: &logging
#   driver: loki
#   options:
#     # loki-url: "http://loki:3100/loki/api/v1/push"
#     loki-url: "http://localhost:3100/loki/api/v1/push"

services:
  webhook:
    image: webhook:latest
    container_name: webhook
    command: ["-verbose", "-hooks=/etc/webhook/hooks.yaml", "-hotreload"]
    ports:
      - "9000:9000"
    volumes:
      - ./webhook/hooks.yaml:/etc/webhook/hooks.yaml
      - ./webhook/hooks/scripts:/etc/webhook/hooks/scripts
    # logging: *logging
    # depends_on:
    #   - loki
    # restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  hoge.com:
    image: nginx:latest
    container_name: hoge.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/ssl:/etc/nginx/ssl
    # logging: *logging
    # depends_on:
    #   - loki
    extra_hosts:
      - "host.docker.internal:host-gateway"

  client:
    image: tls-example-client
    container_name: client
    # build:
    #   context: .
    #   dockerfile: ./compose/client/Dockerfile
    volumes:
      - ./root-ca/pki/cert/rootCA.crt:/usr/local/share/ca-certificates/rootCA.crt
      # - ./root-ca/pki/cert/intermediateCA.crt:/usr/local/share/ca-certificates/intermediateCA.crt
    tty: true
    # logging: *logging
    # depends_on:
    #   - loki
    extra_hosts:
      - "host.docker.internal:host-gateway"



  # root-ca:
  #   image: root-ca:latest
  #   container_name: root-ca
  #   hostname: root-ca
  #   volumes:
  #     - ./root-ca/pki:/etc/pki
  #   tty: true
  #   stdin_open: true
  #   # logging: *logging
  #   # depends_on:
  #   #   - loki
  #   # restart: always
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
